### ISSUE TITLE
Talvikilometrikisa 2021

### ISSUE THREAD

**Issue by hugovk** [jaamo/strava2kilometrikisa#40]
## Expected behavior

Site is working to sync km from Strava to Kilometrikisa. 

## Current behavior

This site can’t be reached
strava2kilometrikisa.com took too long to respond.
Try:

Checking the connection
ERR_CONNECTION_TIMED_OUT

## Steps to reproduce

1. Go to https://strava2kilometrikisa.com/

**Comment by jaamo** [comment]
The app is using mLab MongoDB for persistent storage and mLab is now deprecated. Reason for timeout is that the database doesn't exists anymore.

Let's see if I can migrate to MondoDB Atlas.

**Comment by jaamo** [comment]
I made an update:

- Updated some packages
- Moved database from mLab to MongoDB Atlas
- Removed Kampiapina promotion since I'm not the only contributor anymore 👍 
- Updated competition id

Should work now :)

**Comment by hugovk** [comment]
Thanks! 

https://www.strava2kilometrikisa.com/ (with www) is working now!

Although I'm still getting ERR_CONNECTION_TIMED_OUT at https://strava2kilometrikisa.com/ (no www), which is the one linked in the README. Can it be redirected?

**Comment by hugovk** [comment]
I have automatic synchronization enabled, and the manual sync from 4 days ago worked, but it's not done any autosync since then.

**Comment by hugovk** [comment]
I've been doing a manual sync every day or two, but 20.1.2021 is the last successful day:


https://www.strava2kilometrikisa.com/manualsync

![image](https://user-images.githubusercontent.com/1324225/106437014-79acf600-647d-11eb-97c6-5d4dfbfb9040.png)

![image](https://user-images.githubusercontent.com/1324225/106437115-9812f180-647d-11eb-9968-a5f3ff544f1c.png)

https://www.kilometrikisa.fi/contest/log/

![image](https://user-images.githubusercontent.com/1324225/106437146-a19c5980-647d-11eb-927f-41be2af50727.png)

**Comment by hugovk** [comment]
Just noticed when I clicked "Ok" it then went to https://www.strava2kilometrikisa.com/account and then said my session had timed out (would be good to show that on the "success" page). I logged back in and manual sync now works. Will check if auto sync works.

**Comment by hugovk** [comment]
Autosync not working, manual sync is working.
